gems: [jekyll-paginate]

title: Gonza Robaina

paginate: 3
paginate_path: "/blog/page:num/"

collections:
  - work
  - study
  - portfolio

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Montevideo
future:      true
